version: '3.7'

services:
  assistant-lk:
    container_name: assistant-lk
    build:
      context: .
      dockerfile: _docker/dev/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8025:5173'
    command: npm run dev -- --host