name: Deploy on Main Branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Setup environment
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Run make build
      run: |
        make build
